### ISSUE TITLE
Full example

### ISSUE THREAD

**Issue by alex84G** [nathanforce/react-register-nodes#1]
Hi,
I saw your article and example on your Blog (https://palmer.net/blog/form-field-scroll-management-in-react).

Can you provide a full example, how to use the manager an target components?

**Comment by nathanforce** [comment]
Hey thanks for reading!

https://codesandbox.io/s/jjlpm54z0w

Here's a Codesandbox demonstrating the basic usage.  It's a bit clunky but it can be composed nicely into your own `<FormField>` component or something similar.

I'll try to update this to hooks which will hopefully enable a cleaner API.

Thanks!
